//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialCrm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBankProcesses
    {
        public int BankProcessId { get; set; }
        public string BankProcessDescription { get; set; }
        public Nullable<System.DateTime> BankProcessDate { get; set; }
        public string BankProcessType { get; set; }
        public Nullable<decimal> BankProcessAmount { get; set; }
        public Nullable<int> BankProcessFKBankId { get; set; }
    
        public virtual TblBanks TblBanks { get; set; }
    }
}
